// TypeScript code generated by Nori Code Generator

import { Locale, Configuration } from '@nori'

const { preferredLocale } = Configuration
// preferredLocale is 'undefined'

export const nori = {
                /** Client-specific messages. */
        client: {
                {
client.welcome-to-nori: ( params: { 
/** The name of the user. */
username: string
 } ) => string;
}
                {
client.good-morning: ( params: { 

 } ) => string;
}
        } as const,
} as const;