// goal of typescript code generate is to take a NoriState and produce code to easily let users interact with i18n in their projects

import { NoriCollection, NoriEntry, NoriManager } from "@nori/state-loader/index.js";
import {
	NoriEntryParamType,
	NoriLocale,
	NoriLocaleMeta
} from "@nori/state-loader/state-loader-types.js";
import type { ICodeGenerator } from "../index.js";

const ParamTypeToTsString: Record<NoriEntryParamType, string> = {
	[NoriEntryParamType.String]: "string",
	[NoriEntryParamType.Number]: "number",
	[NoriEntryParamType.Boolean]: "boolean"
} as const;

export class MethodNotImplementedError extends Error {
	constructor(methodName: string) {
		super(`Method ${methodName} is not implemented.`);
		this.name = "MethodNotImplementedError";
	}
}

export class TypeScriptCodeGenerator implements ICodeGenerator {
	public formatIdStringToKeyString(id: string): string {
		const entryNameIndex = id.lastIndexOf(".");
		if (entryNameIndex !== -1) {
			id = id.substring(entryNameIndex + 1);
		}
		return `${id
			.replace(/[.\-_]/g, " ")
			.split(" ")
			.map((word, index) => {
				if (index === 0) return word.toLowerCase();
				return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
			})
			.join("")}`;
	}

	public generateCode(): string {
		return this.generateFileHeader() + "\n\n" + this.generateManager();
	}

	public generateFileHeader(): string {
		return `
// TypeScript code generated by Nori Code Generator

import { NoriLocale, createNoriI18nCollection, isNoriI18nCollection } from '@nori';
`;
	}

	public generateManager(): string {
		return `
export const nori = {
${Array.from(NoriManager.collections.values())
	.map((collection) => this.generateCollection(collection))
	.join(",\n")}
`;
	}

	public generateCollection(collection: NoriCollection): string {
		return `
${this.formatIdStringToKeyString(collection.id)}: {
  ${Array.from(collection.entries.values())
		.map((entry) => this.generateEntry(entry))
		.join(",\n")}
} as const,
},
`;
	}

	public generateEntryFunctionSignature(entry: NoriEntry): string {
		const hasParams = entry.params && Object.values(entry.params).length > 0;
		const paramsString = hasParams
			? `params: {
${Object.entries(entry.params)
	.map(([paramKey, { type, default: defaultValue, description, optional = "false" }]) => {
		const lines: string[] = [];
		const parts: string[] = [];

		// add description if exists
		if (description) {
			const descriptionString =
				typeof description === "string"
					? description
					: description[NoriLocale.EnglishBritish];
			lines.push(`/** ${descriptionString} */`);
		}

		// determine ts type
		const tsType = ParamTypeToTsString[type];
		if (!tsType)
			throw new Error(
				`Unsupported parameter type: ${type} for parameter ${paramKey} in entry ${entry.id}`
			);

		// build parameter line
		parts.push(`\t\t\t${paramKey}: ${tsType}`);

		// if default value, include undefined in type
		if (defaultValue !== undefined || optional === "true") parts.push("| undefined");

		return [...lines, parts.join(" ")].join("\n");
	})
	.join("\n")}
\t\t}`
			: "";
		return `(${paramsString})`;
	}

	public generateEntryFunctionBody(entry: NoriEntry): string {
		return `
${
	entry.params && Object.values(entry.params).length > 0
		? `
\t\t\tconst { ${Object.entries(entry.params)
				.map(([paramKey, { default: defaultValue }]) => {
					if (defaultValue !== undefined) {
						return `${paramKey} = ${JSON.stringify(defaultValue)}`;
					} else {
						return paramKey;
					}
				})
				.join(", ")} } = params;`
		: ""
}
\t\t\treturn {
${Object.values(NoriLocale)
	.map((localeKey) => {
		const localeString = entry.locales?.[localeKey] ?? `${entry.id} [${localeKey}]`;
		return `\t\t\t\t[NoriLocale.${NoriLocaleMeta.reverseLookup(
			localeKey
		)}]: \`${localeString.replace(/{{\s*(\w+)\s*}}/g, "${$1}")}\``;
	})
	.join(",\n")}
\t\t\t};
`;
	}

	public generateEntry(entry: NoriEntry): string {
		return `
${this.formatIdStringToKeyString(
	entry.id
)}: createNoriI18nCollection(${this.generateEntryFunctionSignature(entry)} => {
${this.generateEntryFunctionBody(entry)}
	})
`;
	}
}
