// TypeScript code generated by Nori Code Generator

import { NoriLocale, NoriI18nCollection } from "../cli/src/core/index.js";

export const nori = {
  /** Client-specific messages. */
  client: {
    welcomeToNori: (params: {
      /** The name of the user. */
      username: string | undefined;
    }): NoriI18nCollection => {
      const { username = "guest" } = params;
      return {
        [NoriLocale.EnglishBritish]: `Welcome to Nori, ${username}!`,
        [NoriLocale.Japanese]: `ノリへようこそ、${username}さん！`,
      };
    },
    goodMorning: (): NoriI18nCollection => {
      return {
        [NoriLocale.EnglishBritish]: `Good morning!`,
        [NoriLocale.Japanese]: `おはようございます！`,
      };
    },
  } as const,
} as const;
