// TypeScript code generated by Nori Code Generator

import {
  NoriLocale,
  createNoriI18nCollection,
  isNoriI18nCollection,
} from "@nori";

export const nori = {
  client: {
    welcomeToNori: createNoriI18nCollection(
      (params: {
        /** The name of the user. */
        username: string | undefined;
      }) => {
        const { username = "guest" } = params;
        return {
          [NoriLocale.EnglishBritish]: `Welcome to Nori, ${username}!`,
          [NoriLocale.Japanese]: `ノリへようこそ、${username}さん！`,
        };
      },
    ),
    goodMorning: createNoriI18nCollection(() => {
      return {
        [NoriLocale.EnglishBritish]: `Good morning!`,
        [NoriLocale.Japanese]: `おはようございます！`,
      };
    }),
  } as const,
};
